version: '3.9'

services:
    mysql:
        image: mysql:8.0
        container_name: mysql_shoe_db
        restart: always
        environment:
            MYSQL_DATABASE: citimed_db
            MYSQL_USER: citimed_user
            MYSQL_PASSWORD: citimed@2025
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
