name: Deploy Citimed App to Prod

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '20.19.2'

      - name: Install dependencies
        run: |
          npm install

      - name: Install livewire/flux if missing
        run: |
          npm install livewire/flux

      - name: Build project for production
        run: |
          npm run build

      - name: Move build assets to the correct location
        run: |
          mv public/build/assets/app-C3Ox5C8m.css citimedhospital.co.ke/public/build/assets/
          mv public/build/assets/app-l0sNRNKZ.js citimedhospital.co.ke/public/build/assets/

      - name: Zip project contents (excluding unnecessary files)
        run: |
          zip -r app.zip . -x \
            "vendor/**" \
            "node_modules/**" \
            ".git/**" \
            ".github/**" \
            "tests/**" \
            "*.md" \
            ".env"

      - name: Upload zipped contents via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{secrets.FTP_HOST}}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: /domains/citimedhospital.co.ke/
